# Generated by https://smithery.ai. 
# For more information, see https://github.com/smithery-ai/smithery-cli/blob/main/README.md#docker
FROM python:3.10-slim-buster

# Set working directory
WORKDIR /app

# Copy dependency files
COPY requirements.txt .
COPY pyproject.toml .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY main.py .

# Expose no ports as this is a stdio server

# Entry point to run the MCP server
ENTRYPOINT ["python", "main.py"]
